### ISSUE TITLE
Not compatible with Sketch Version 3.2

### ISSUE THREAD

**Issue by FreeleticsDanny** [bomberstudios/sketch-generator#11]
- Plugin can not be used in current Sketch Version. No Files were exported.

**Comment by adominomono** [comment]
not working for me either.

also, what are Rules,
Name the layer or layer group using the rules in the Rules section (i.e: 'button.png, button@2x.png 200%')

wheres the Rules section?, that word is not to be found in Sketch from i can see, we have Ruler(s), people do take things quite literally, you mean the Layers?

yea confused.

**Comment by levitabris** [comment]
I also tried the sample.sketch file in the package. Didn't work on 3.2 version neither.
